### ISSUE TITLE
Use osmosdr repository compatible with gr3.8

### ISSUE THREAD

**Issue by F4HVO** [krippendorf/setup_sdr#2]
I had to change the gr-osmosdr repository to compile it successfully.
I used https://github.com/igorauad/gr-osmosdr.git (it is still needed to checkout branch gr3.8).
Tested on a fresh ubuntu 18.04.4 LTS install.

**Comment by hb9fxq** [comment]
Probably error was due to too old cmake version. This is now fixed, recent cmake is installed from ppa. It builds the gr3.8 branch of the official osmocom repo.
